<a href="https://colab.research.google.com/github/Satish-Kumar-1/Basics-Deep-learning-projects/blob/main/Pytorch_training_from_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [10]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')


In [11]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [12]:
df.sample(5)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
236  88299702         M        23.21         26.97          153.50     1670.0   
36     854268         M        14.25         21.72           93.63      633.0   
514  91594602         M        15.05         19.07           97.26      701.9   
418    906024         B        12.70         12.17           80.88      495.0   
237    883263         M        20.48         21.46          132.50     1306.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
236          0.09509           0.16820         0.19500              0.12370   
36           0.09823           0.10980         0.13190              0.05598   
514          0.09215           0.08597         0.07486              0.04335   
418          0.08785           0.05794         0.02360              0.02402   
237          0.08355           0.08348         0.09042              0.06022   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
236  ...          34.51           206.00      2944.0            0.1481   
36   ...          30.36           116.20       799.6            0.1446   
514  ...          28.06           113.80       967.0            0.1246   
418  ...          16.92            88.12       566.9            0.1314   
237  ...          26.17           161.70      1750.0            0.1228   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
236             0.4126          0.58200               0.25930          0.3103   
36              0.4238          0.51860               0.14470          0.3591   
514             0.2101          0.28660               0.11200          0.2282   
418             0.1607          0.09385               0.08224          0.2775   
237             0.2311          0.31580               0.14450          0.2238   

     fractal_dimension_worst  Unnamed: 32  
236                  0.08677          NaN  
36                   0.10140          NaN  
514                  0.06954          NaN  
418                  0.09464          NaN  
237                  0.07127          NaN  

[5 rows x 33 columns]

In [13]:
df = df.drop(columns = ['id', 'Unnamed: 32'])

In [14]:
df.shape

(569, 31)

# Train_test_split


In [15]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size = 0.2)


In [17]:
# Scaling

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [18]:
x_train

array([[-0.59256775, -1.50576571, -0.62744906, ..., -0.68838302,
        -0.6490478 , -0.28951433],
       [-0.07830045, -0.01397217, -0.1467572 , ..., -0.51794051,
        -0.91031249, -0.45580611],
       [-0.3717682 ,  0.4748771 , -0.39336951, ..., -0.90412536,
        -0.69204072, -0.14689799],
       ...,
       [ 0.44714657,  0.82831742,  0.53931015, ...,  1.32889875,
         0.60766847,  2.31591145],
       [-0.84970139, -1.2005218 , -0.85384724, ..., -1.15850133,
        -0.54652621, -0.78557116],
       [ 0.88595073,  0.86274342,  0.75357986, ..., -0.50506263,
        -0.75156939, -1.06911274]])

In [19]:
y_train

158    B
481    B
407    B
106    B
252    M
      ..
358    B
203    M
118    M
354    B
261    M
Name: diagnosis, Length: 455, dtype: object

In [21]:
# LabelEncoder

encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [22]:
y_train

array([0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,

# Numpy arrays to PyTorch tensors

In [23]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [24]:
x_train_tensor.shape

torch.Size([455, 30])

In [34]:
print(y_train_tensor.shape)
print(y_pred.shape)

torch.Size([455])
torch.Size([455, 30])


# Define the Model

In [35]:
class MySimpleNN():

    def __init__(self, x):

        self.weights = torch.rand(x.shape[1], 1, dtype = torch.float64, requires_grad = True)
        self.bias = torch.zeros(1, dtype = torch.float64, requires_grad = True)

    def forward(self, x):

        z= torch.matmul(x, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
        loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
        return loss

In [36]:
# Some important paramters

learning_rate = 0.1
epochs = 25


# Train the model

In [38]:
model = MySimpleNN(x_train_tensor)

for epoch in range(epochs):
    y_pred = model.forward(x_train_tensor)

    loss = model.loss_function(y_pred, y_train_tensor)

    loss.backward()

    with torch.no_grad():
        model.weights -=  learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.803316944546535
Epoch: 2, Loss: 3.68745518127038
Epoch: 3, Loss: 3.5684560381052624
Epoch: 4, Loss: 3.4409915980609305
Epoch: 5, Loss: 3.3048055939141157
Epoch: 6, Loss: 3.16482231561994
Epoch: 7, Loss: 3.023807110064895
Epoch: 8, Loss: 2.8823996225479096
Epoch: 9, Loss: 2.737006206482173
Epoch: 10, Loss: 2.5896876510393856
Epoch: 11, Loss: 2.439707043890504
Epoch: 12, Loss: 2.289794954535856
Epoch: 13, Loss: 2.139357331122192
Epoch: 14, Loss: 1.9883413075421519
Epoch: 15, Loss: 1.8362096618237638
Epoch: 16, Loss: 1.6895898961609919
Epoch: 17, Loss: 1.5518941022531763
Epoch: 18, Loss: 1.419155654103915
Epoch: 19, Loss: 1.2998897975730122
Epoch: 20, Loss: 1.1950319919722328
Epoch: 21, Loss: 1.1050623799957928
Epoch: 22, Loss: 1.0298025038209502
Epoch: 23, Loss: 0.9683223989399291
Epoch: 24, Loss: 0.919027711128525
Epoch: 25, Loss: 0.879920056528884


In [39]:
model.bias

tensor([-0.1156], dtype=torch.float64, requires_grad=True)

# Evaluation

In [40]:
with torch.no_grad():
    y_pred = model.forward(x_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy is : {accuracy.item()}')

Accuracy is : 0.592336118221283
