<a href="https://colab.research.google.com/github/Satish-Kumar-1/Basics-Deep-learning-projects/blob/main/USE_NN_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn


In [15]:
class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out


In [16]:
x = torch.rand(10, 5)

In [17]:
model = Model(x.shape[1])

model(x)

tensor([[0.4009],
        [0.4011],
        [0.4011],
        [0.4009],
        [0.4009],
        [0.4011],
        [0.4009],
        [0.4011],
        [0.4008],
        [0.4024]], grad_fn=<SigmoidBackward0>)

In [18]:
model.linear1.bias

Parameter containing:
tensor([-0.1964,  0.1453, -0.0888], requires_grad=True)

In [21]:
print(f'Weights of 1 layer {model.linear1.weight} and the weights of 2 layer is {model.linear2.weight}')

Weights of 1 layer Parameter containing:
tensor([[-0.2482,  0.0584, -0.3540, -0.0245, -0.3689],
        [-0.3478, -0.4147,  0.1183, -0.4392,  0.2097],
        [ 0.3080,  0.2440,  0.0365, -0.4017,  0.1583]], requires_grad=True) and the weights of 2 layer is Parameter containing:
tensor([[-0.2422,  0.2026, -0.0047]], requires_grad=True)


In [23]:
!pip install torchinfo

In [25]:
from torchinfo import summary
summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [27]:
# Sequential Container

class Model1(nn.Module):

    def __init__(self, num_features):
        super().__init__()

        self.layers = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.Relu(),
            nn.Linear(3, 1),
            nn.Sigmoid()


        )

    def forward(self, x):
        out = self.layers(x)

        return out

In [28]:
model1 = Model(x.shape[1])

In [29]:
summary(model1, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [30]:
model1(x)

tensor([[0.6928],
        [0.6717],
        [0.6585],
        [0.6838],
        [0.6742],
        [0.6535],
        [0.6933],
        [0.6609],
        [0.6866],
        [0.6336]], grad_fn=<SigmoidBackward0>)

In [31]:
summary(model1, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00